/* Generated By:JavaCC: Do not edit this line. JVCParserConstants.java */
package com.pmdesigns.jvc.tools;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JVCParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int START_CODE_TAG = 1;
  /** RegularExpression Id. */
  int START_EXPR_TAG = 2;
  /** RegularExpression Id. */
  int START_EXPR2_TAG = 3;
  /** RegularExpression Id. */
  int START_LOAD_TAG = 4;
  /** RegularExpression Id. */
  int START_COMMENT_TAG = 5;
  /** RegularExpression Id. */
  int EOL = 6;
  /** RegularExpression Id. */
  int START_CACHE_BLOCK = 7;
  /** RegularExpression Id. */
  int END_CACHE_BLOCK = 8;
  /** RegularExpression Id. */
  int END_TAG = 9;
  /** RegularExpression Id. */
  int IMPORT = 10;
  /** RegularExpression Id. */
  int WS = 11;
  /** RegularExpression Id. */
  int ALPHA = 12;
  /** RegularExpression Id. */
  int DIGIT = 13;
  /** RegularExpression Id. */
  int ID = 14;
  /** RegularExpression Id. */
  int ESCAPED_CHAR = 15;
  /** RegularExpression Id. */
  int OTHER = 16;

  /** Lexical state. */
  int IN_COMMENT = 0;
  /** Lexical state. */
  int IN_LOAD = 1;
  /** Lexical state. */
  int IN_EXPR2 = 2;
  /** Lexical state. */
  int IN_EXPR = 3;
  /** Lexical state. */
  int IN_CODE = 4;
  /** Lexical state. */
  int DEFAULT = 5;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"[[\"",
    "\"[[=\"",
    "\"[[==\"",
    "\"[[+\"",
    "\"[[!\"",
    "<EOL>",
    "<START_CACHE_BLOCK>",
    "<END_CACHE_BLOCK>",
    "<END_TAG>",
    "<IMPORT>",
    "<WS>",
    "<ALPHA>",
    "<DIGIT>",
    "<ID>",
    "<ESCAPED_CHAR>",
    "<OTHER>",
  };

}
